name: Scheduled Redeploy

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Make a fake commit to trigger redeploy
        run: |
          echo "$(date)" > timestamp.txt
          git add timestamp.txt
          git commit -m "Trigger redeploy at $(date)" || echo "No changes to commit"
          git push origin HEAD:master
